# Generated by Django 4.2.11 on 2024-05-05 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_appusermodel_app_objects'),
        ('dynamic_models', '0002_vendor_schoolorder_order_log_kit_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prev_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='prev_level_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='training_level',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('object_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('completed_level', models.CharField(max_length=255)),
                ('current_level', models.CharField(max_length=255)),
                ('center_name', models.CharField(max_length=255)),
                ('center_address', models.TextField()),
                ('punctuality', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('attention_to_instructor', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('problem_solving_skills', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('innovative_method', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('teaching_method', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('sharing_experiences', models.CharField(choices=[('Satisfactory', 'Satisfactory'), ('Unsatisfactory', 'Unsatisfactory')], max_length=15)),
                ('comments_suggestions', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('teacher', zelthy.apps.dynamic_models.fields.ZForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dynamic_models.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
