# Generated by Django 4.2.11 on 2024-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_teacher_due_date_teacher_prev_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='prev_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='training_level',
            field=models.IntegerField(null=True),
        ),
    ]
