# Generated by Django 4.2.11 on 2024-05-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_alter_teacher_prev_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingDate',
        ),
    ]
