# Generated by Django 4.2.11 on 2024-05-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0006_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolorder',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
