# Generated by Django 4.2.11 on 2024-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0008_remove_enquiry_timestamp_alter_enquiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='kits',
            field=models.JSONField(null=True),
        ),
    ]
