# Generated by Django 4.2.11 on 2024-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0009_alter_order_items_alter_order_kits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolorder',
            name='items',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='schoolorder',
            name='kits',
            field=models.JSONField(null=True),
        ),
    ]
