# Generated by Django 4.2.11 on 2024-05-13 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_appusermodel_app_objects'),
        ('dynamic_models', '0010_alter_schoolorder_items_alter_schoolorder_kits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('object_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('certificate_request', 'Certificate Request'), ('birthday', 'Birthday'), ('training_due_date', 'Training Due Date'), ('competition_announcement', 'Competition Announcement'), ('order', 'Order'), ('other', 'Other')], max_length=50)),
                ('account_type', models.CharField(choices=[('franchise', 'Franchise'), ('admin', 'Admin'), ('teacher', 'Teacher')], max_length=50)),
                ('details', models.TextField(blank=True, default='Details Not Available')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('franchise', zelthy.apps.dynamic_models.fields.ZForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynamic_models.franchisee')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
