# Generated by Django 4.2.11 on 2024-05-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelcertificate',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='levelcertificate',
            name='programme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
