# Generated by Django 4.2.11 on 2024-05-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0013_alter_levelcertificate_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelcertificate',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
