# Generated by Django 4.2.11 on 2024-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0015_alter_levelcertificate_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('certificate_request', 'Certificate Request'), ('birthday', 'Birthday'), ('training_due_date', 'Training Due Date'), ('competition_announcement', 'Competition Announcement'), ('order', 'Order'), ('enquiry', 'Enquiry'), ('other', 'Other')], max_length=50),
        ),
    ]
