# Generated by Django 4.2.11 on 2024-05-24 19:14

from django.db import migrations
import django.db.models.deletion
import zelthy.apps.dynamic_models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0021_alter_item_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kit',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kit_name', to='dynamic_models.kit'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='franchise',
            field=zelthy.apps.dynamic_models.fields.ZForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dynamic_models.franchisee'),
        ),
    ]
