# Generated by Django 4.2.11 on 2024-05-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0023_alter_student_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
