# Generated by Django 4.2.11 on 2024-05-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0024_alter_student_course_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionstudent',
            unique_together={('competition', 'franchise')},
        ),
    ]
