# Generated by Django 4.2.11 on 2024-05-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0007_schoolorder_delivery_date_alter_log_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
