# Generated by Django 4.2.11 on 2024-05-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0022_alter_item_kit_alter_notification_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_start_date',
            field=models.DateField(blank=True),
        ),
    ]
