# Generated by Django 4.2.15 on 2024-12-01 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zango.apps.dynamic_models.mixin


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0006_appusermodel_app_objects'),
        ('dynamic_models', '0028_alter_stat_students_alter_stat_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('object_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='appauth.appusermodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, zango.apps.dynamic_models.mixin.DynamicModelMixin),
        ),
    ]
