# Generated by Django 4.2.15 on 2024-12-01 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0029_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
