# Generated by Django 4.2.15 on 2024-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0031_alter_testimonial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('senior', 'Senior'), ('none', 'None')], max_length=10, null=True),
        ),
    ]
